name: flutter_shared_extra
description: A new Flutter package project.
version: 1.0.1
author:
homepage: distantfutu.re

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_parsed_text: ^1.2.4
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  stream_transform: ^1.2.0
  google_sign_in: ^4.5.1
  provider: ^4.1.2
  cloud_functions: ^0.5.0
  flutter_keyboard_visibility: ^2.0.0
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7
  bubble: ^1.1.9+1
  intl_phone_number_input: ^0.4.2
  image: ^2.1.13

  flutter_shared:
    # git: git://github.com/sgehrman/flutter_shared
    # git: ssh://git@github.com/sgehrman/flutter_shared
    path: ../flutter_shared

dev_dependencies:
  lint: ^1.2.0

flutter:
  uses-material-design: true
