name: flutter_shared_extra
description: A new Flutter package project.
version: 1.0.1
author:
homepage: distantfutu.re

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_parsed_text: ^1.2.4
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  stream_transform: ^1.2.0
  google_sign_in: ^4.4.6
  provider: ^4.1.2
  cloud_functions: ^0.5.0
  flutter_keyboard_visibility: ^2.0.0
  firebase_storage: ^3.1.5
  image_picker: ^0.6.6+1
  bubble: ^1.1.9+1
  intl_phone_number_input: ^0.4.1
  image: ^2.1.12

  flutter_shared:
    # git: git://github.com/sgehrman/flutter_shared
    git: ssh://git@github.com/sgehrman/flutter_shared

dev_dependencies:
  lint: ^1.2.0

flutter:
  uses-material-design: true
