name: flutter_shared_extra
description: A new Flutter package project.
version: 1.0.1
author: null
homepage: distantfutu.re
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bubble: ^1.1.9+1
  cloud_firestore: ^0.14.4
  cloud_functions: ^0.7.2
  firebase_auth: ^0.18.4+1
  firebase_storage: ^5.2.0

  flutter_keyboard_visibility: ^4.0.2
  flutter_multi_formatter: ^1.3.0
  flutter_parsed_text: ^1.2.5

  flutter_shared:
    # git: git://github.com/sgehrman/flutter_shared
    # git: ssh://git@github.com/sgehrman/flutter_shared
    path: ../flutter_shared

  google_sign_in: ^4.5.6
  image: ^2.1.19
  image_picker: ^0.6.7+17
  provider: ^4.3.2+3
  stream_transform: ^1.2.0

dev_dependencies:
  lint: ^1.5.1

flutter:
  uses-material-design: true
